### PR TITLE
v0.1.0

### PR DESCRIPTION
**Pull request by GregoryAlbouy**
## Description

⚠️ **NO MERGE**

### CODE REVIEW

**Comment by moreirathomas** [comment]
Genuine question : why have a release branch when we can tag commits and then release that tag from the release tab ?

It seems way easier to me. Especially because it offers archive files automatically on the release page. Plus tags seems meant for that.

Capture d’écran 2022-02-20 à 12 31 06

Capture d’écran 2022-02-20 à 12 31 26

**Comment by GregoryAlbouy** [comment]
Genuine answer: no idea, just experimenting stuff 😛 

Could allow to perform additional CI check (e2e healthcheck) by securing the branch.
Could also trigger some CD workflow workflow on merge on `release`, but that is certainly also doable on release tag itself.
Also having a branch of only release commits seemed nice, but again it's only experimenting 🤷‍♂️

**Comment by moreirathomas** [comment]
Ok ! 🙂 

CI seems already taken care of by the CI on each merge into `main`.
CD works on `release` events too ! I've actually done some experiments on that myself a few days ago: [moreirathomas/gh-actions-sandbox](https://github.com/moreirathomas/gh-actions-sandbox). The repo has some basic experiments, but I tried tools like [release-it](https://github.com/release-it/release-it) or [action-gh-release](https://github.com/softprops/action-gh-release) and they seem nice !

> Also having a branch of only release commits seemed nice, but again it's only experimenting 🤷‍♂️

That's `main` 😛 .

**Comment by GregoryAlbouy** [comment]
> CI seems already taken care of by the CI on each merge into `main`.

**_additional_** check is the key word here. 

> That's `main` 😛 .

It's not 😕

Any harm in experimenting this?

**Comment by moreirathomas** [comment]
> Any harm in experimenting this?

None at all, just discussing it 🙂

**Pull request closed without merging**
